version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: go_backend_demo
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

